### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by charlespctech** [mistralol/srip#2]
I get the following error when I run ./autogen.sh && make on a new install of ubuntu 18.04

configure.ac:12: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:19: error: possibly undefined macro: AC_SUBST
configure.ac:36: error: possibly undefined macro: AC_MSG_ERROR
autoreconf: /usr/bin/autoconf failed with exit status: 1
configure: error: cannot find install-sh, install.sh, or shtool in config "."/config

**Comment by mistralol** [comment]
You need to have a number of packages installed in order to build and run. This should be at least

autoconf autoconf-archive libtool-bin gstreamer1.0-tools libgstreamer1.0-dev gstreamer1.0-plugins-bad
gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-pulseaudio

They may be others as well.

**Comment by mistralol** [comment]
I updated the README.md to include these

**Comment by charlespctech** [comment]
I also had to install these to get it to compile. 

libdbus-1-dev libjson-glib-dev libjsoncpp-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-dev libgstreamer1.0-dev gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad gstreamer1.0-plugins-good 

then I installed pavucontrol to change the recording source. Thank you!

**Comment by mistralol** [comment]
Thanks for that btw. I finally got around to updating the readme.
